# -*- coding: utf-8 -*-
"""TwoPoints_Cartesian_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dHe9PQ_52p2fU0Ix0jxI02t1r7Kz55ZV
"""

X1 = int(input("Choose the value of X for the first point ")) 
X2 = int(input("Choose the value of y for the first point ")) 
X3 = int(input("Choose the value of X for the second point: ")) 
X4 = int(input("Choose the value of Y for the second point: "))
print()

def vef_quad1(X1,X2):
  if X1 >= 0 and X2 >= 0:
    return "first quadrant." 
  elif X1 <= 0 and X2 >= 0:
    return "second quadrant."
  elif X1 <=0 and X2 <=0:
    return "third quadrant."
  elif X1 >= 0 and X2 <= 0:
    return "fourth quadrant."

def vef_quad2(X3,X4):
  if X3 >= 0 and X4 >= 0:
    return "first quadrant." 
  elif X3 <= 0 and X4 >= 0:
    return "second quadrant."
  elif X3 <=0 and X4 <=0:
    return "third quadrant."
  elif X3 >= 0 and X4 <= 0:
    return "fourth quadrant."    

print("Coordinate at the first point:", X1,",", X2)
quad = vef_quad1(X1,X2)
print("The first point is found in", quad)
print("Coordinate at the second point", X3,",", X4)
quad1 = vef_quad2(X3,X4)
print("The second point is found in", quad1)
print()
Distancia_pontos = ((X1 - X3)**2 + (X2 - X4)**2)**0.5
print("The distance between the two points is", Distancia_pontos)
print()
print("End.")